services:
  db:
    image: postgres:15-alpine
    container_name: iot-final-db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: iot-final-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  monitor:
    build: .
    container_name: iot-final-monitor
    command: python monitor.py
    env_file:
      - .env
    depends_on:
      - api

volumes:
  pgdata: